#!/bin/bash
# scripts/verify-pagination-max.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 4: Pagination Max ==="

SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

# Check pagination configuration exists
MAX_PAGE_SIZE=$(jq '.pagination.maxPageSize // empty' "$SERVICE_CONTRACTS")
DEFAULT_PAGE_SIZE=$(jq '.pagination.defaultPageSize // empty' "$SERVICE_CONTRACTS")
ENFORCEMENT=$(jq -r '.pagination.enforcement // empty' "$SERVICE_CONTRACTS")

if [[ -n "$MAX_PAGE_SIZE" ]]; then
  echo "  [OK] maxPageSize: $MAX_PAGE_SIZE"
else
  echo "  [X] maxPageSize not declared"
  VIOLATIONS=$((VIOLATIONS + 1))
fi

if [[ -n "$DEFAULT_PAGE_SIZE" ]]; then
  echo "  [OK] defaultPageSize: $DEFAULT_PAGE_SIZE"
else
  echo "  [X] defaultPageSize not declared"
  VIOLATIONS=$((VIOLATIONS + 1))
fi

if [[ -n "$ENFORCEMENT" ]]; then
  echo "  [OK] enforcement: $ENFORCEMENT"
else
  echo "  [X] enforcement not declared"
  VIOLATIONS=$((VIOLATIONS + 1))
fi

# Verify default <= max
if [[ -n "$MAX_PAGE_SIZE" && -n "$DEFAULT_PAGE_SIZE" ]]; then
  if [[ $DEFAULT_PAGE_SIZE -le $MAX_PAGE_SIZE ]]; then
    echo "  [OK] defaultPageSize ($DEFAULT_PAGE_SIZE) <= maxPageSize ($MAX_PAGE_SIZE)"
  else
    echo "  [X] defaultPageSize ($DEFAULT_PAGE_SIZE) > maxPageSize ($MAX_PAGE_SIZE)"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS pagination violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Pagination max verified"
exit 0
