#!/bin/bash
# scripts/verify-project-scope-strategy.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 3: Project Scope Strategy ==="

DATA_REL="$PROJECT_ROOT/docs/data-relationships.json"
VIOLATIONS=0

if [[ ! -f "$DATA_REL" ]]; then
  echo "[FAIL] data-relationships.json not found"
  exit 1
fi

# All indirect-tenant tables must have projectScopeStrategy
TABLE_COUNT=$(jq '.tables | length' "$DATA_REL")
if [[ $TABLE_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((TABLE_COUNT - 1))); do
    table_name=$(jq -r ".tables[$i].name" "$DATA_REL")
    tenant_key=$(jq -r ".tables[$i].tenantKey" "$DATA_REL")

    if [[ "$tenant_key" == "indirect" ]]; then
      scope_strategy=$(jq -r ".tables[$i].projectScopeStrategy // empty" "$DATA_REL")
      required_filtering=$(jq ".tables[$i].requiredFiltering // [] | length" "$DATA_REL")

      if [[ -n "$scope_strategy" ]]; then
        echo "  [OK] $table_name: projectScopeStrategy=$scope_strategy"
      else
        echo "  [X] $table_name: indirect tenant but no projectScopeStrategy"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi

      if [[ $required_filtering -gt 0 ]]; then
        echo "  [OK] $table_name: requiredFiltering declared ($required_filtering rules)"
      else
        echo "  [X] $table_name: indirect tenant but no requiredFiltering"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS project scope strategy violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Project scope strategy verified"
exit 0
