#!/bin/bash
# scripts/verify-no-wildcard-cors.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 2: No Wildcard CORS ==="

VIOLATIONS=0

# Derive source directories from artifact file paths
SEARCH_DIRS=()
for artifact in "$PROJECT_ROOT/docs/service-contracts.json" \
  "$PROJECT_ROOT/docs/data-relationships.json" \
  "$PROJECT_ROOT/docs/ui-api-deps.json" \
  "$PROJECT_ROOT/docs/env-manifest.json"; do
  if [[ -f "$artifact" ]]; then
    while IFS= read -r dir; do
      if [[ -n "$dir" && -d "$PROJECT_ROOT/$dir" ]]; then
        SEARCH_DIRS+=("$dir")
      fi
    done < <(grep -oP '"[^"]*\.(ts|tsx|js|jsx)"' "$artifact" | tr -d '"' | sed 's|/.*||' | sort -u)
  fi
done
SEARCH_DIRS=($(printf '%s\n' "${SEARCH_DIRS[@]}" | sort -u))

if [[ ${#SEARCH_DIRS[@]} -eq 0 ]]; then
  echo "  [SKIP] No source directories found (pre-implementation)"
  echo ""
  echo "[PASS] No wildcard CORS (no source to check)"
  exit 0
fi

for dir in "${SEARCH_DIRS[@]}"; do
  if [[ -d "$PROJECT_ROOT/$dir" ]]; then
    # Search for literal wildcard CORS origin
    wildcard_hits=$(grep -rn "origin.*['\"]\\*['\"]" "$PROJECT_ROOT/$dir" --include="*.ts" --include="*.js" 2>/dev/null || true)
    if [[ -n "$wildcard_hits" ]]; then
      echo "  [X] Wildcard CORS found in $dir:"
      echo "$wildcard_hits" | head -5
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  fi
done

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS wildcard CORS violation(s)"
  exit 1
fi

echo "  [OK] No wildcard CORS origins detected"
echo ""
echo "[PASS] No wildcard CORS"
exit 0
