#!/bin/bash
# scripts/verify-env-manifest-schema.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 2: Env Manifest Schema ==="

ENV_MANIFEST="$PROJECT_ROOT/docs/env-manifest.json"
VIOLATIONS=0

if [[ ! -f "$ENV_MANIFEST" ]]; then
  echo "[FAIL] env-manifest.json not found"
  exit 1
fi

# Validate JSON syntax
if ! jq empty "$ENV_MANIFEST" 2>/dev/null; then
  echo "[FAIL] env-manifest.json is not valid JSON"
  exit 1
fi

# Check required sections
for section in "required" "optional"; do
  if jq -e ".$section" "$ENV_MANIFEST" > /dev/null 2>&1; then
    echo "  [OK] Section: $section"
  else
    echo "  [X] Missing section: $section"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi
done

# Each required entry must have 6 fields: name, usage, validation, validatedInFile, usedInFiles, whyRequired
REQ_COUNT=$(jq '.required | length' "$ENV_MANIFEST")
if [[ $REQ_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((REQ_COUNT - 1))); do
    env_name=$(jq -r ".required[$i].name" "$ENV_MANIFEST")
    REQUIRED_KEYS=("name" "usage" "validation" "validatedInFile" "usedInFiles" "whyRequired")
    missing_keys=""
    for key in "${REQUIRED_KEYS[@]}"; do
      has_key=$(jq -r ".required[$i] | has(\"$key\")" "$ENV_MANIFEST")
      if [[ "$has_key" != "true" ]]; then
        missing_keys="$missing_keys $key"
      fi
    done
    if [[ -z "$missing_keys" ]]; then
      echo "  [OK] $env_name: all 6 fields present"
    else
      echo "  [X] $env_name: missing fields:$missing_keys"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS env manifest schema violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Env manifest schema valid"
exit 0
