#!/bin/bash
# scripts/verify-endpoint-status.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 4: Endpoint Status ==="

SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

ENDPOINT_COUNT=$(jq '.endpoints | length' "$SERVICE_CONTRACTS")
REQUIRED_COUNT=0
DEFERRED_COUNT=0

if [[ $ENDPOINT_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((ENDPOINT_COUNT - 1))); do
    ep_status=$(jq -r ".endpoints[$i].status" "$SERVICE_CONTRACTS")
    ep_method=$(jq -r ".endpoints[$i].method" "$SERVICE_CONTRACTS")
    ep_path=$(jq -r ".endpoints[$i].path" "$SERVICE_CONTRACTS")

    if [[ "$ep_status" == "required" ]]; then
      REQUIRED_COUNT=$((REQUIRED_COUNT + 1))
      echo "  [OK] REQUIRED: $ep_method $ep_path"
    elif [[ "$ep_status" == "deferred" ]]; then
      DEFERRED_COUNT=$((DEFERRED_COUNT + 1))
      echo "  [--] DEFERRED: $ep_method $ep_path"
    else
      echo "  [X] UNKNOWN STATUS '$ep_status': $ep_method $ep_path"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  done
fi

echo ""
echo "  Required: $REQUIRED_COUNT | Deferred: $DEFERRED_COUNT | Total: $ENDPOINT_COUNT"

if [[ $REQUIRED_COUNT -eq 0 ]]; then
  echo "  [X] No required endpoints found"
  VIOLATIONS=$((VIOLATIONS + 1))
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS endpoint status violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Endpoint status verified"
exit 0
