#!/bin/bash
# scripts/verify-spec-size-budget.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Preflight: Spec Size Budget ==="

MAX_SPEC_SIZE_KB=500
VIOLATIONS=0

SPEC_FILES=(
  "docs/scope-manifest.json"
  "docs/env-manifest.json"
  "docs/data-relationships.json"
  "docs/service-contracts.json"
  "docs/ui-api-deps.json"
)

for spec in "${SPEC_FILES[@]}"; do
  if [[ -f "$PROJECT_ROOT/$spec" ]]; then
    size_kb=$(du -k "$PROJECT_ROOT/$spec" | cut -f1)
    if [[ $size_kb -gt $MAX_SPEC_SIZE_KB ]]; then
      echo "  [X] $spec: ${size_kb}KB exceeds ${MAX_SPEC_SIZE_KB}KB budget"
      VIOLATIONS=$((VIOLATIONS + 1))
    else
      echo "  [OK] $spec: ${size_kb}KB"
    fi
  fi
done

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS spec(s) exceed size budget"
  exit 1
fi

echo ""
echo "[PASS] All specs within size budget"
exit 0
