#!/bin/bash
# scripts/verify-preflight-artifacts.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Preflight: Required Specification Artifacts ==="

MISSING=0

REQUIRED_SPECS=(
  "docs/scope-manifest.json"
  "docs/env-manifest.json"
  "docs/data-relationships.json"
  "docs/service-contracts.json"
  "docs/ui-api-deps.json"
  "docs/gate-scripts-reference.md"
)

for spec in "${REQUIRED_SPECS[@]}"; do
  if [[ -f "$PROJECT_ROOT/$spec" ]]; then
    echo "  [OK] $spec"
  else
    echo "  [MISSING] $spec"
    MISSING=$((MISSING + 1))
  fi
done

if [[ $MISSING -gt 0 ]]; then
  echo ""
  echo "[FAIL] $MISSING specification artifact(s) missing"
  exit 1
fi

echo ""
echo "[PASS] All 6 specification artifacts present"
exit 0
