#!/bin/bash
# scripts/verify-scope-invariants.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 1: Scope Invariants ==="

SCOPE_MANIFEST="$PROJECT_ROOT/docs/scope-manifest.json"
VIOLATIONS=0

if [[ ! -f "$SCOPE_MANIFEST" ]]; then
  echo "[FAIL] scope-manifest.json not found"
  exit 1
fi

# Check required schema fields
REQUIRED_FIELDS=("requiredEntities" "deferredEntities" "platformConstraints" "userRoles" "entityContracts")
for field in "${REQUIRED_FIELDS[@]}"; do
  if jq -e ".$field" "$SCOPE_MANIFEST" > /dev/null 2>&1; then
    echo "  [OK] Field: $field"
  else
    echo "  [X] Missing field: $field"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi
done

# Verify every requiredEntity has an entityContract
ENTITY_COUNT=$(jq '.requiredEntities | length' "$SCOPE_MANIFEST")
if [[ $ENTITY_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((ENTITY_COUNT - 1))); do
    entity=$(jq -r ".requiredEntities[$i]" "$SCOPE_MANIFEST")
    has_contract=$(jq --arg e "$entity" '.entityContracts | has($e)' "$SCOPE_MANIFEST")
    if [[ "$has_contract" == "true" ]]; then
      echo "  [OK] Entity contract: $entity"
    else
      echo "  [X] Missing entity contract for: $entity"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  done
fi

# Verify multiTenancy is defined
if jq -e '.platformConstraints.multiTenancy.isolationField' "$SCOPE_MANIFEST" > /dev/null 2>&1; then
  echo "  [OK] Multi-tenancy isolation field defined"
else
  echo "  [X] Missing multi-tenancy isolation field"
  VIOLATIONS=$((VIOLATIONS + 1))
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS scope invariant violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Scope invariants verified"
exit 0
