#!/bin/bash
# scripts/verify-route-service-alignment.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 4: Route-Service Alignment ==="

SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

ENDPOINT_COUNT=$(jq '.endpoints | length' "$SERVICE_CONTRACTS")
if [[ $ENDPOINT_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((ENDPOINT_COUNT - 1))); do
    ep_status=$(jq -r ".endpoints[$i].status" "$SERVICE_CONTRACTS")
    if [[ "$ep_status" != "required" ]]; then
      continue
    fi

    ep_method=$(jq -r ".endpoints[$i].method" "$SERVICE_CONTRACTS")
    ep_path=$(jq -r ".endpoints[$i].path" "$SERVICE_CONTRACTS")
    ep_route_file=$(jq -r ".endpoints[$i].routeFile // empty" "$SERVICE_CONTRACTS")
    ep_service_file=$(jq -r ".endpoints[$i].serviceContract.serviceFile // empty" "$SERVICE_CONTRACTS")
    ep_method_name=$(jq -r ".endpoints[$i].serviceContract.methodName // empty" "$SERVICE_CONTRACTS")

    # Verify route file is declared
    if [[ -z "$ep_route_file" ]]; then
      echo "  [X] $ep_method $ep_path: no routeFile declared"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi

    # Verify service file is declared
    if [[ -z "$ep_service_file" ]]; then
      echo "  [X] $ep_method $ep_path: no serviceFile declared"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi

    # Verify method name is declared
    if [[ -z "$ep_method_name" ]]; then
      echo "  [X] $ep_method $ep_path: no methodName declared"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi

    # If files exist, verify alignment
    if [[ -n "$ep_route_file" && -f "$PROJECT_ROOT/$ep_route_file" ]]; then
      # Check that route file references service method
      if [[ -n "$ep_method_name" ]]; then
        if grep -q "$ep_method_name" "$PROJECT_ROOT/$ep_route_file"; then
          echo "  [OK] $ep_method $ep_path: route -> $ep_method_name"
        else
          echo "  [X] $ep_method $ep_path: route file does not reference $ep_method_name"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      fi
    else
      echo "  [SKIP] $ep_method $ep_path: files not yet created (pre-implementation)"
    fi

    # Rule 8: Check for error-swallowing anti-pattern
    if [[ -n "$ep_route_file" && -f "$PROJECT_ROOT/$ep_route_file" ]]; then
      if grep -Pzo 'catch\s*\([^)]*\)\s*\{[^}]*res\.status\(500\)' "$PROJECT_ROOT/$ep_route_file" > /dev/null 2>&1; then
        if ! grep -Pzo 'catch\s*\([^)]*\)\s*\{[^}]*(error\s+instanceof|error\.name|error\.status)' "$PROJECT_ROOT/$ep_route_file" > /dev/null 2>&1; then
          echo "  [!] WARNING: $ep_route_file may contain error-swallowing catch block (Anti-Pattern 4)"
        fi
      fi
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS route-service alignment violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Route-service alignment verified"
exit 0
