#!/bin/bash
# scripts/verify-no-forbidden-artifacts.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Preflight: No Forbidden Artifacts ==="

# Deferred entities from scope-manifest.json
SCOPE_MANIFEST="$PROJECT_ROOT/docs/scope-manifest.json"
VIOLATIONS=0

if [[ ! -f "$SCOPE_MANIFEST" ]]; then
  echo "[SKIP] scope-manifest.json not found"
  exit 0
fi

DEFERRED_COUNT=$(jq '.deferredEntities | length' "$SCOPE_MANIFEST")
if [[ $DEFERRED_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((DEFERRED_COUNT - 1))); do
    deferred_name=$(jq -r ".deferredEntities[$i].name" "$SCOPE_MANIFEST")

    # Check deferralDeclarations for this entity
    db_schema_file=$(jq -r ".deferralDeclarations.${deferred_name}.database.schemaFile // empty" "$SCOPE_MANIFEST")
    route_file=$(jq -r ".deferralDeclarations.${deferred_name}.api.routeFile // empty" "$SCOPE_MANIFEST")

    # Schema file must NOT exist (deferred)
    if [[ -n "$db_schema_file" && -f "$PROJECT_ROOT/$db_schema_file" ]]; then
      echo "  [X] Forbidden: $db_schema_file exists (deferred entity: $deferred_name)"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi

    # Route file must NOT exist (deferred)
    if [[ -n "$route_file" && -f "$PROJECT_ROOT/$route_file" ]]; then
      echo "  [X] Forbidden: $route_file exists (deferred entity: $deferred_name)"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi

    # Service files must NOT exist (deferred)
    svc_count=$(jq ".deferralDeclarations.${deferred_name}.services.files | length" "$SCOPE_MANIFEST" 2>/dev/null || echo "0")
    if [[ $svc_count -gt 0 ]]; then
      for j in $(seq 0 $((svc_count - 1))); do
        svc_file=$(jq -r ".deferralDeclarations.${deferred_name}.services.files[$j]" "$SCOPE_MANIFEST")
        if [[ -n "$svc_file" && -f "$PROJECT_ROOT/$svc_file" ]]; then
          echo "  [X] Forbidden: $svc_file exists (deferred entity: $deferred_name)"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      done
    fi

    # UI page files must NOT exist (deferred)
    page_count=$(jq ".deferralDeclarations.${deferred_name}.ui.pages | length" "$SCOPE_MANIFEST" 2>/dev/null || echo "0")
    if [[ $page_count -gt 0 ]]; then
      for j in $(seq 0 $((page_count - 1))); do
        page_file=$(jq -r ".deferralDeclarations.${deferred_name}.ui.pages[$j].componentFile" "$SCOPE_MANIFEST")
        if [[ -n "$page_file" && -f "$PROJECT_ROOT/$page_file" ]]; then
          echo "  [X] Forbidden: $page_file exists (deferred entity: $deferred_name)"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      done
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS forbidden artifact(s) found for deferred entities"
  exit 1
fi

echo "  [OK] No forbidden artifacts for deferred entities"
echo ""
echo "[PASS] No forbidden artifacts detected"
exit 0
