#!/bin/bash
# scripts/verify-config-files-required.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 2: Config Files Required ==="

ENV_MANIFEST="$PROJECT_ROOT/docs/env-manifest.json"
VIOLATIONS=0

if [[ ! -f "$ENV_MANIFEST" ]]; then
  echo "[FAIL] env-manifest.json not found"
  exit 1
fi

# Verify that validatedInFile targets exist
REQ_COUNT=$(jq '.required | length' "$ENV_MANIFEST")
if [[ $REQ_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((REQ_COUNT - 1))); do
    env_name=$(jq -r ".required[$i].name" "$ENV_MANIFEST")
    validated_in=$(jq -r ".required[$i].validatedInFile // empty" "$ENV_MANIFEST")
    if [[ -n "$validated_in" ]]; then
      if [[ -f "$PROJECT_ROOT/$validated_in" ]]; then
        echo "  [OK] $env_name: $validated_in exists"
      else
        echo "  [SKIP] $env_name: $validated_in not yet created (pre-implementation)"
      fi
    fi
  done
fi

# Verify that usedInFiles targets exist
if [[ $REQ_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((REQ_COUNT - 1))); do
    env_name=$(jq -r ".required[$i].name" "$ENV_MANIFEST")
    used_count=$(jq ".required[$i].usedInFiles | length" "$ENV_MANIFEST")
    if [[ $used_count -gt 0 ]]; then
      for j in $(seq 0 $((used_count - 1))); do
        used_file=$(jq -r ".required[$i].usedInFiles[$j]" "$ENV_MANIFEST")
        if [[ -f "$PROJECT_ROOT/$used_file" ]]; then
          echo "  [OK] $env_name: $used_file exists"
        else
          echo "  [SKIP] $env_name: $used_file not yet created (pre-implementation)"
        fi
      done
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS config file(s) missing"
  exit 1
fi

echo ""
echo "[PASS] Config files verified"
exit 0
