#!/bin/bash
# scripts/verify-health-db-connectivity.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 2: Health & DB Connectivity ==="

SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

# Find health endpoint by purpose, not by hardcoded path
HEALTH_ENDPOINT=$(jq -r '[.endpoints[] | select(.serviceContract.purpose == "healthCheck")] | .[0] // empty' "$SERVICE_CONTRACTS")

if [[ -z "$HEALTH_ENDPOINT" || "$HEALTH_ENDPOINT" == "null" ]]; then
  echo "  [X] No health check endpoint found (purpose: healthCheck)"
  VIOLATIONS=$((VIOLATIONS + 1))
else
  HEALTH_ROUTE_FILE=$(echo "$HEALTH_ENDPOINT" | jq -r '.routeFile // empty')
  HEALTH_SERVICE_FILE=$(echo "$HEALTH_ENDPOINT" | jq -r '.serviceContract.serviceFile // empty')
  HEALTH_PATH=$(echo "$HEALTH_ENDPOINT" | jq -r '.path // empty')

  echo "  Health endpoint: $HEALTH_PATH"

  # Verify route file exists
  if [[ -n "$HEALTH_ROUTE_FILE" && -f "$PROJECT_ROOT/$HEALTH_ROUTE_FILE" ]]; then
    echo "  [OK] Route file: $HEALTH_ROUTE_FILE"
  else
    echo "  [SKIP] Route file: $HEALTH_ROUTE_FILE not yet created (pre-implementation)"
  fi

  # Verify service file exists
  if [[ -n "$HEALTH_SERVICE_FILE" && -f "$PROJECT_ROOT/$HEALTH_SERVICE_FILE" ]]; then
    echo "  [OK] Service file: $HEALTH_SERVICE_FILE"
  else
    echo "  [SKIP] Service file: $HEALTH_SERVICE_FILE not yet created (pre-implementation)"
  fi
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS health/db connectivity violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Health & DB connectivity verified"
exit 0
