#!/bin/bash
# scripts/verify-upload-e2e.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 4: Upload E2E ==="

SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

# Find upload endpoints (fileUpload: true)
UPLOAD_ENDPOINTS=$(jq '[.endpoints[] | select(.serviceContract.fileUpload == true and .status == "required")]' "$SERVICE_CONTRACTS")
UPLOAD_COUNT=$(echo "$UPLOAD_ENDPOINTS" | jq 'length')

if [[ $UPLOAD_COUNT -eq 0 ]]; then
  echo "  [OK] No upload endpoints declared"
  echo ""
  echo "[PASS] Upload E2E (no uploads)"
  exit 0
fi

echo "  Found $UPLOAD_COUNT upload endpoint(s)"

for i in $(seq 0 $((UPLOAD_COUNT - 1))); do
  ep_method=$(echo "$UPLOAD_ENDPOINTS" | jq -r ".[$i].method")
  ep_path=$(echo "$UPLOAD_ENDPOINTS" | jq -r ".[$i].path")
  ep_route_file=$(echo "$UPLOAD_ENDPOINTS" | jq -r ".[$i].routeFile // empty")
  ep_service_file=$(echo "$UPLOAD_ENDPOINTS" | jq -r ".[$i].serviceContract.serviceFile // empty")
  ep_max_size=$(echo "$UPLOAD_ENDPOINTS" | jq -r ".[$i].maxSizeMb // empty")
  ep_allowed_mimes=$(echo "$UPLOAD_ENDPOINTS" | jq -r ".[$i].allowedMimeTypes // [] | length")

  echo "  Upload: $ep_method $ep_path"

  # Must have middleware including multer or similar upload handler
  mw_count=$(echo "$UPLOAD_ENDPOINTS" | jq ".[$i].middleware | length")
  if [[ $mw_count -gt 0 ]]; then
    echo "    [OK] Middleware stack: $mw_count middleware(s)"
  else
    echo "    [X] No middleware declared for upload endpoint"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi

  # Must have allowed MIME types
  if [[ $ep_allowed_mimes -gt 0 ]]; then
    echo "    [OK] Allowed MIME types: $ep_allowed_mimes"
  else
    echo "    [X] No allowed MIME types declared"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi

  # Must have max size
  if [[ -n "$ep_max_size" ]]; then
    echo "    [OK] Max size: ${ep_max_size}MB"
  else
    echo "    [X] No maxSizeMb declared"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi
done

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS upload E2E violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Upload E2E verified"
exit 0
