#!/bin/bash
# scripts/verify-complete-deferrals.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 1: Complete Deferrals ==="

SCOPE_MANIFEST="$PROJECT_ROOT/docs/scope-manifest.json"
VIOLATIONS=0

if [[ ! -f "$SCOPE_MANIFEST" ]]; then
  echo "[FAIL] scope-manifest.json not found"
  exit 1
fi

# Each deferred entity must have a complete deferralDeclaration
DEFERRED_COUNT=$(jq '.deferredEntities | length' "$SCOPE_MANIFEST")
if [[ $DEFERRED_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((DEFERRED_COUNT - 1))); do
    entity_name=$(jq -r ".deferredEntities[$i].name" "$SCOPE_MANIFEST")
    has_declaration=$(jq --arg e "$entity_name" '.deferralDeclarations | has($e)' "$SCOPE_MANIFEST")

    if [[ "$has_declaration" == "true" ]]; then
      # Check required sub-fields
      has_reason=$(jq -r ".deferralDeclarations.${entity_name} | has(\"reason\")" "$SCOPE_MANIFEST")
      has_db=$(jq -r ".deferralDeclarations.${entity_name} | has(\"database\")" "$SCOPE_MANIFEST")
      has_api=$(jq -r ".deferralDeclarations.${entity_name} | has(\"api\")" "$SCOPE_MANIFEST")
      has_ui=$(jq -r ".deferralDeclarations.${entity_name} | has(\"ui\")" "$SCOPE_MANIFEST")

      if [[ "$has_reason" == "true" && "$has_db" == "true" && "$has_api" == "true" && "$has_ui" == "true" ]]; then
        echo "  [OK] $entity_name: complete deferral declaration"
      else
        echo "  [X] $entity_name: incomplete deferral (reason=$has_reason db=$has_db api=$has_api ui=$has_ui)"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi
    else
      echo "  [X] $entity_name: missing deferralDeclaration"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  done
fi

# Deferred entities must NOT appear in requiredEntities
if [[ $DEFERRED_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((DEFERRED_COUNT - 1))); do
    entity_name=$(jq -r ".deferredEntities[$i].name" "$SCOPE_MANIFEST")
    in_required=$(jq --arg e "$entity_name" '[.requiredEntities[] | select(. == $e)] | length' "$SCOPE_MANIFEST")
    if [[ $in_required -gt 0 ]]; then
      echo "  [X] $entity_name appears in BOTH requiredEntities and deferredEntities"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS deferral violation(s)"
  exit 1
fi

echo ""
echo "[PASS] All deferrals complete"
exit 0
