#!/bin/bash
# scripts/verify-status-enums.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 4: Status Enums ==="

SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
DATA_REL="$PROJECT_ROOT/docs/data-relationships.json"
VIOLATIONS=0

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

# Verify each statusEnum declared in service-contracts has matching data model
ENUM_COUNT=$(jq '.statusEnums | length' "$SERVICE_CONTRACTS")
if [[ $ENUM_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((ENUM_COUNT - 1))); do
    enum_name=$(jq -r ".statusEnums[$i].name" "$SERVICE_CONTRACTS")
    enum_field=$(jq -r ".statusEnums[$i].statusField" "$SERVICE_CONTRACTS")
    api_values=$(jq -r ".statusEnums[$i].allowedValues | sort | join(\",\")" "$SERVICE_CONTRACTS")

    echo "  Entity: $enum_name (field: $enum_field)"
    echo "    API values: $api_values"

    # Cross-check with data-relationships.json
    if [[ -f "$DATA_REL" ]]; then
      db_values=$(jq -r --arg t "$enum_name" --arg f "$enum_field" \
        '[.tables[] | select(.name == $t) | .columns[] | select(.name == $f) | .values[]?] | sort | join(",")' "$DATA_REL")

      if [[ -n "$db_values" ]]; then
        echo "    DB values:  $db_values"
        if [[ "$api_values" == "$db_values" ]]; then
          echo "    [OK] API and DB enum values match"
        else
          echo "    [X] API and DB enum values MISMATCH"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      else
        echo "    [SKIP] No DB enum values found for $enum_name.$enum_field"
      fi
    fi

    # Verify transitions reference valid values
    transition_count=$(jq ".statusEnums[$i].transitions | length" "$SERVICE_CONTRACTS")
    if [[ $transition_count -gt 0 ]]; then
      for j in $(seq 0 $((transition_count - 1))); do
        from_val=$(jq -r ".statusEnums[$i].transitions[$j].from" "$SERVICE_CONTRACTS")
        to_vals=$(jq -r ".statusEnums[$i].transitions[$j].to | join(\",\")" "$SERVICE_CONTRACTS")

        # Check from is in allowedValues
        is_valid_from=$(jq --argjson idx "$i" --arg f "$from_val" \
          '[.statusEnums[$idx].allowedValues[] | select(. == $f)] | length' "$SERVICE_CONTRACTS")
        if [[ $is_valid_from -eq 0 ]]; then
          echo "    [X] Transition 'from' value '$from_val' not in allowedValues"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      done
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS status enum violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Status enums verified"
exit 0
