#!/bin/bash
# scripts/verify-ui-canonical-paths.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 5: UI Canonical Paths ==="

UI_DEPS="$PROJECT_ROOT/docs/ui-api-deps.json"
VIOLATIONS=0

if [[ ! -f "$UI_DEPS" ]]; then
  echo "[FAIL] ui-api-deps.json not found"
  exit 1
fi

# Check canonical paths
CANONICAL_PATHS=$(jq -r '.canonicalPaths | keys[]' "$UI_DEPS" 2>/dev/null || true)
for key in $CANONICAL_PATHS; do
  canonical_file=$(jq -r ".canonicalPaths.$key" "$UI_DEPS")
  if [[ -f "$PROJECT_ROOT/$canonical_file" ]]; then
    echo "  [OK] $key: $canonical_file exists"
  else
    echo "  [SKIP] $key: $canonical_file not yet created (pre-implementation)"
  fi
done

# Verify total pages count matches declared
DECLARED_TOTAL=$(jq '.totalPages' "$UI_DEPS")
ACTUAL_TOTAL=$(jq '.pages | length' "$UI_DEPS")

if [[ "$DECLARED_TOTAL" == "$ACTUAL_TOTAL" ]]; then
  echo "  [OK] totalPages ($DECLARED_TOTAL) matches pages array length ($ACTUAL_TOTAL)"
else
  echo "  [X] totalPages ($DECLARED_TOTAL) != pages array length ($ACTUAL_TOTAL)"
  VIOLATIONS=$((VIOLATIONS + 1))
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS UI canonical path violation(s)"
  exit 1
fi

echo ""
echo "[PASS] UI canonical paths verified"
exit 0
