#!/bin/bash
# scripts/verify-ui-self-consistency.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 5: UI Self-Consistency ==="

UI_DEPS="$PROJECT_ROOT/docs/ui-api-deps.json"
VIOLATIONS=0

if [[ ! -f "$UI_DEPS" ]]; then
  echo "[FAIL] ui-api-deps.json not found"
  exit 1
fi

# Check for duplicate route paths
PAGE_COUNT=$(jq '.pages | length' "$UI_DEPS")
if [[ $PAGE_COUNT -gt 0 ]]; then
  # Extract route paths and check for duplicates
  ROUTES=$(jq -r '.pages[].routePath' "$UI_DEPS" | sort)
  UNIQUE_ROUTES=$(echo "$ROUTES" | sort -u)
  ROUTE_COUNT=$(echo "$ROUTES" | wc -l)
  UNIQUE_COUNT=$(echo "$UNIQUE_ROUTES" | wc -l)

  if [[ $ROUTE_COUNT -eq $UNIQUE_COUNT ]]; then
    echo "  [OK] No duplicate route paths ($ROUTE_COUNT routes)"
  else
    echo "  [X] Duplicate route paths detected"
    echo "$ROUTES" | uniq -d
    VIOLATIONS=$((VIOLATIONS + 1))
  fi

  # Check for duplicate file paths
  FILES=$(jq -r '.pages[].filePath' "$UI_DEPS" | sort)
  UNIQUE_FILES=$(echo "$FILES" | sort -u)
  FILE_COUNT=$(echo "$FILES" | wc -l)
  UNIQUE_FILE_COUNT=$(echo "$UNIQUE_FILES" | wc -l)

  if [[ $FILE_COUNT -eq $UNIQUE_FILE_COUNT ]]; then
    echo "  [OK] No duplicate file paths ($FILE_COUNT files)"
  else
    echo "  [X] Duplicate file paths detected"
    echo "$FILES" | uniq -d
    VIOLATIONS=$((VIOLATIONS + 1))
  fi

  # Required pages must have authenticated flag
  for i in $(seq 0 $((PAGE_COUNT - 1))); do
    page_scope=$(jq -r ".pages[$i].scope" "$UI_DEPS")
    page_file=$(jq -r ".pages[$i].filePath" "$UI_DEPS")
    has_auth=$(jq ".pages[$i] | has(\"authenticated\")" "$UI_DEPS")

    if [[ "$page_scope" == "required" && "$has_auth" != "true" ]]; then
      echo "  [X] $page_file: missing 'authenticated' field"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS UI self-consistency violation(s)"
  exit 1
fi

echo ""
echo "[PASS] UI self-consistency verified"
exit 0
