#!/bin/bash
# scripts/verify-cascade-completeness.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 3: Cascade Completeness ==="

DATA_REL="$PROJECT_ROOT/docs/data-relationships.json"
VIOLATIONS=0

if [[ ! -f "$DATA_REL" ]]; then
  echo "[FAIL] data-relationships.json not found"
  exit 1
fi

# Each cascade target table must exist in tables[]
CASCADE_COUNT=$(jq '.softDeleteCascades | length' "$DATA_REL")
if [[ $CASCADE_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((CASCADE_COUNT - 1))); do
    parent=$(jq -r ".softDeleteCascades[$i].parentEntity" "$DATA_REL")
    target_count=$(jq ".softDeleteCascades[$i].cascadeTargets | length" "$DATA_REL")

    # Verify parent exists in tables
    parent_exists=$(jq --arg p "$parent" '[.tables[] | select(.name == $p)] | length' "$DATA_REL")
    if [[ $parent_exists -eq 0 ]]; then
      echo "  [X] Cascade parent '$parent' not found in tables[]"
      VIOLATIONS=$((VIOLATIONS + 1))
    fi

    if [[ $target_count -gt 0 ]]; then
      for j in $(seq 0 $((target_count - 1))); do
        target_table=$(jq -r ".softDeleteCascades[$i].cascadeTargets[$j].table" "$DATA_REL")
        target_fk=$(jq -r ".softDeleteCascades[$i].cascadeTargets[$j].foreignKey" "$DATA_REL")

        # Verify target table exists
        target_exists=$(jq --arg t "$target_table" '[.tables[] | select(.name == $t)] | length' "$DATA_REL")
        if [[ $target_exists -eq 0 ]]; then
          echo "  [X] Cascade target '$target_table' (parent: $parent) not found in tables[]"
          VIOLATIONS=$((VIOLATIONS + 1))
        else
          # Verify FK column exists on target table
          fk_exists=$(jq --arg t "$target_table" --arg fk "$target_fk" \
            '[.tables[] | select(.name == $t) | .columns[] | select(.name == $fk)] | length' "$DATA_REL")
          if [[ $fk_exists -gt 0 ]]; then
            echo "  [OK] $parent -> $target_table.$target_fk"
          else
            echo "  [X] $parent -> $target_table.$target_fk: FK column not found"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi
        fi
      done
    fi
  done
fi

# Verify execution order is sequential
if [[ $CASCADE_COUNT -gt 1 ]]; then
  orders=$(jq '[.softDeleteCascades[].executionOrder] | sort | unique | length' "$DATA_REL")
  total_orders=$(jq '.softDeleteCascades | length' "$DATA_REL")
  if [[ $orders -eq $total_orders ]]; then
    echo "  [OK] Cascade execution orders are unique"
  else
    echo "  [X] Duplicate cascade execution orders detected"
    VIOLATIONS=$((VIOLATIONS + 1))
  fi
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS cascade completeness violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Cascade completeness verified"
exit 0
