#!/bin/bash
# scripts/verify-no-placeholders.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Preflight: No Placeholders in Specs ==="

VIOLATIONS=0
PLACEHOLDER_PATTERNS="TODO|FIXME|PLACEHOLDER|XXX|HACK"

SPEC_FILES=(
  "docs/scope-manifest.json"
  "docs/env-manifest.json"
  "docs/data-relationships.json"
  "docs/service-contracts.json"
  "docs/ui-api-deps.json"
)

for spec in "${SPEC_FILES[@]}"; do
  if [[ -f "$PROJECT_ROOT/$spec" ]]; then
    hits=$(grep -ciE "$PLACEHOLDER_PATTERNS" "$PROJECT_ROOT/$spec" || true)
    if [[ $hits -gt 0 ]]; then
      echo "  [X] $spec: $hits placeholder(s) found"
      grep -niE "$PLACEHOLDER_PATTERNS" "$PROJECT_ROOT/$spec" | head -5
      VIOLATIONS=$((VIOLATIONS + 1))
    else
      echo "  [OK] $spec: clean"
    fi
  fi
done

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS spec(s) contain placeholders"
  exit 1
fi

echo ""
echo "[PASS] No placeholders in specification artifacts"
exit 0
