#!/bin/bash
# scripts/verify-multi-tenant-isolation.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Preflight: Multi-Tenant Isolation ==="

SCOPE_MANIFEST="$PROJECT_ROOT/docs/scope-manifest.json"
DATA_REL="$PROJECT_ROOT/docs/data-relationships.json"
SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$SCOPE_MANIFEST" ]]; then
  echo "[SKIP] scope-manifest.json not found"
  exit 0
fi

# Read tenant isolation field from scope-manifest
ISOLATION_FIELD=$(jq -r '.platformConstraints.multiTenancy.isolationField // empty' "$SCOPE_MANIFEST")
if [[ -z "$ISOLATION_FIELD" ]]; then
  echo "[SKIP] No isolation field defined"
  exit 0
fi

echo "  Isolation field: $ISOLATION_FIELD"

# Verify direct-tenant tables have the isolation column
if [[ -f "$DATA_REL" ]]; then
  TABLE_COUNT=$(jq '.tables | length' "$DATA_REL")
  if [[ $TABLE_COUNT -gt 0 ]]; then
    for i in $(seq 0 $((TABLE_COUNT - 1))); do
      table_name=$(jq -r ".tables[$i].name" "$DATA_REL")
      tenant_key=$(jq -r ".tables[$i].tenantKey" "$DATA_REL")

      if [[ "$tenant_key" == "direct" ]]; then
        has_iso_col=$(jq --arg t "$table_name" --arg col "$ISOLATION_FIELD" \
          '[.tables[] | select(.name == $t) | .columns[] | select(.name == $col)] | length' "$DATA_REL")
        if [[ $has_iso_col -gt 0 ]]; then
          echo "  [OK] $table_name has $ISOLATION_FIELD column (direct tenant)"
        else
          echo "  [X] $table_name MISSING $ISOLATION_FIELD column (direct tenant)"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      fi
    done
  fi
fi

# Verify token-scoped endpoints use auth for tenant isolation
if [[ -f "$SERVICE_CONTRACTS" ]]; then
  ENDPOINT_COUNT=$(jq '.endpoints | length' "$SERVICE_CONTRACTS")
  if [[ $ENDPOINT_COUNT -gt 0 ]]; then
    for i in $(seq 0 $((ENDPOINT_COUNT - 1))); do
      ep_status=$(jq -r ".endpoints[$i].status" "$SERVICE_CONTRACTS")
      ep_must_use_auth=$(jq -r ".endpoints[$i].serviceContract.mustUseAuth // false" "$SERVICE_CONTRACTS")
      ep_auth_required=$(jq -r ".endpoints[$i].serviceContract.authRequired" "$SERVICE_CONTRACTS")
      ep_path=$(jq -r ".endpoints[$i].path" "$SERVICE_CONTRACTS")
      ep_method=$(jq -r ".endpoints[$i].method" "$SERVICE_CONTRACTS")

      if [[ "$ep_status" == "required" && "$ep_must_use_auth" == "true" && "$ep_auth_required" == "true" ]]; then
        # Check if endpoint is explicitly documented as platform-level (no org filter)
        ep_notes=$(jq -r --argjson idx "$i" '.endpoints[$idx].serviceContract.notes // ""' "$SERVICE_CONTRACTS")
        if echo "$ep_notes" | grep -qi "No organisationId filter"; then
          echo "  [OK] $ep_method $ep_path is platform-level resource (exempt from tenant isolation)"
        else
          # Check that route args include an auth-derived org reference
          has_org_arg=$(jq --argjson idx "$i" \
            '[.endpoints[$idx].serviceContract.routeArgs[] | select(contains("organisationId") or contains("user.organisationId"))] | length' "$SERVICE_CONTRACTS")
          if [[ $has_org_arg -gt 0 ]]; then
            echo "  [OK] $ep_method $ep_path uses auth-derived tenant scope"
          else
            echo "  [X] $ep_method $ep_path: mustUseAuth=true but no organisationId in routeArgs"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi
        fi
      fi
    done
  fi
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS multi-tenant isolation violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Multi-tenant isolation verified"
exit 0
