#!/bin/bash
# scripts/verify-encryption-binary.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 2: Encryption Binary ==="

ENV_MANIFEST="$PROJECT_ROOT/docs/env-manifest.json"
VIOLATIONS=0

if [[ ! -f "$ENV_MANIFEST" ]]; then
  echo "[SKIP] env-manifest.json not found"
  exit 0
fi

# Check if ENCRYPTION_KEY is declared in conditionallyRequired
ENCRYPTION_DECLARED=$(jq '[.conditionallyRequired[]? | select(.name == "ENCRYPTION_KEY")] | length' "$ENV_MANIFEST")

if [[ $ENCRYPTION_DECLARED -gt 0 ]]; then
  enc_used_in=$(jq -r '[.conditionallyRequired[] | select(.name == "ENCRYPTION_KEY") | .usedInFiles[]?] | .[]' "$ENV_MANIFEST" 2>/dev/null || true)

  if [[ -n "$enc_used_in" ]]; then
    for file in $enc_used_in; do
      if [[ -f "$PROJECT_ROOT/$file" ]]; then
        echo "  [OK] Encryption usage file exists: $file"
      else
        echo "  [SKIP] Encryption usage file: $file not yet created (pre-implementation)"
      fi
    done
  fi

  echo "  [OK] ENCRYPTION_KEY declared in conditionallyRequired"
else
  echo "  [OK] No ENCRYPTION_KEY required (no sensitive data handling)"
fi

echo ""
echo "[PASS] Encryption binary verified"
exit 0
