#!/bin/bash
# scripts/verify-env-var-usage-proof.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Preflight: Env Var Usage Proof ==="

ENV_MANIFEST="$PROJECT_ROOT/docs/env-manifest.json"
VIOLATIONS=0

if [[ ! -f "$ENV_MANIFEST" ]]; then
  echo "[SKIP] env-manifest.json not found"
  exit 0
fi

# Check required env vars
REQ_COUNT=$(jq '.required | length' "$ENV_MANIFEST")
if [[ $REQ_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((REQ_COUNT - 1))); do
    env_name=$(jq -r ".required[$i].name" "$ENV_MANIFEST")
    validated_in=$(jq -r ".required[$i].validatedInFile // empty" "$ENV_MANIFEST")

    if [[ -n "$validated_in" && -f "$PROJECT_ROOT/$validated_in" ]]; then
      if grep -q "$env_name" "$PROJECT_ROOT/$validated_in"; then
        echo "  [OK] $env_name referenced in $validated_in"
      else
        echo "  [X] $env_name NOT referenced in $validated_in"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi
    else
      echo "  [SKIP] $env_name: validation file $validated_in not found (pre-implementation)"
    fi
  done
fi

# Check conditionally required env vars
COND_COUNT=$(jq '.conditionallyRequired | length' "$ENV_MANIFEST")
if [[ $COND_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((COND_COUNT - 1))); do
    env_name=$(jq -r ".conditionallyRequired[$i].name" "$ENV_MANIFEST")
    validated_in=$(jq -r ".conditionallyRequired[$i].validatedInFile // empty" "$ENV_MANIFEST")

    if [[ -n "$validated_in" && -f "$PROJECT_ROOT/$validated_in" ]]; then
      if grep -q "$env_name" "$PROJECT_ROOT/$validated_in"; then
        echo "  [OK] $env_name referenced in $validated_in"
      else
        echo "  [X] $env_name NOT referenced in $validated_in"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi
    else
      echo "  [SKIP] $env_name: validation file $validated_in not found (pre-implementation)"
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS env var(s) not referenced in their declared validation files"
  exit 1
fi

echo ""
echo "[PASS] All env vars have usage proof"
exit 0
