#!/bin/bash
# scripts/verify-ui-api-alignment.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 5: UI-API Alignment ==="

UI_DEPS="$PROJECT_ROOT/docs/ui-api-deps.json"
SERVICE_CONTRACTS="$PROJECT_ROOT/docs/service-contracts.json"
VIOLATIONS=0

if [[ ! -f "$UI_DEPS" ]]; then
  echo "[FAIL] ui-api-deps.json not found"
  exit 1
fi

if [[ ! -f "$SERVICE_CONTRACTS" ]]; then
  echo "[FAIL] service-contracts.json not found"
  exit 1
fi

# Every required API call in a required page must have a matching endpoint in service-contracts
PAGE_COUNT=$(jq '.pages | length' "$UI_DEPS")
if [[ $PAGE_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((PAGE_COUNT - 1))); do
    page_scope=$(jq -r ".pages[$i].scope" "$UI_DEPS")
    page_file=$(jq -r ".pages[$i].filePath" "$UI_DEPS")

    if [[ "$page_scope" != "required" ]]; then
      continue
    fi

    api_count=$(jq ".pages[$i].apiCalls | length" "$UI_DEPS")
    if [[ $api_count -gt 0 ]]; then
      for j in $(seq 0 $((api_count - 1))); do
        api_required=$(jq -r ".pages[$i].apiCalls[$j].required" "$UI_DEPS")
        if [[ "$api_required" != "true" ]]; then
          continue
        fi

        api_method=$(jq -r ".pages[$i].apiCalls[$j].method" "$UI_DEPS")
        api_path=$(jq -r ".pages[$i].apiCalls[$j].path" "$UI_DEPS")

        # Find matching endpoint in service-contracts
        match=$(jq --arg m "$api_method" --arg p "$api_path" \
          '[.endpoints[] | select(.method == $m and .path == $p and .status == "required")] | length' "$SERVICE_CONTRACTS")

        if [[ $match -gt 0 ]]; then
          echo "  [OK] $page_file: $api_method $api_path"
        else
          echo "  [X] $page_file: $api_method $api_path NOT in service-contracts (or not required)"
          VIOLATIONS=$((VIOLATIONS + 1))
        fi
      done
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS UI-API alignment violation(s)"
  exit 1
fi

echo ""
echo "[PASS] UI-API alignment verified"
exit 0
