#!/bin/bash
# scripts/verify-index-strategy.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 3: Index Strategy ==="

DATA_REL="$PROJECT_ROOT/docs/data-relationships.json"
SCOPE_MANIFEST="$PROJECT_ROOT/docs/scope-manifest.json"
VIOLATIONS=0

if [[ ! -f "$DATA_REL" ]]; then
  echo "[FAIL] data-relationships.json not found"
  exit 1
fi

# Read isolation field from scope-manifest
TENANT_FIELD=""
if [[ -f "$SCOPE_MANIFEST" ]]; then
  TENANT_FIELD=$(jq -r '.platformConstraints.multiTenancy.isolationField // empty' "$SCOPE_MANIFEST")
fi

TABLE_COUNT=$(jq '.tables | length' "$DATA_REL")
if [[ $TABLE_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((TABLE_COUNT - 1))); do
    table_name=$(jq -r ".tables[$i].name" "$DATA_REL")
    tenant_key=$(jq -r ".tables[$i].tenantKey" "$DATA_REL")
    sd_col=$(jq -r ".tables[$i].softDeleteColumn // empty" "$DATA_REL")
    index_count=$(jq ".tables[$i].indexes | length" "$DATA_REL")

    # Every table should have at least one index
    if [[ $index_count -eq 0 ]]; then
      echo "  [X] $table_name: no indexes declared"
      VIOLATIONS=$((VIOLATIONS + 1))
      continue
    fi

    echo "  [OK] $table_name: $index_count index(es)"

    # Direct-tenant tables should have an index including the tenant field
    if [[ "$tenant_key" == "direct" && -n "$TENANT_FIELD" ]]; then
      has_tenant_index=$(jq --arg t "$table_name" --arg tf "$TENANT_FIELD" \
        '[.tables[] | select(.name == $t) | .indexes[] | .columns[] | select(. == $tf)] | length' "$DATA_REL")
      if [[ $has_tenant_index -gt 0 ]]; then
        echo "  [OK] $table_name: has index including $TENANT_FIELD"
      else
        echo "  [X] $table_name: direct tenant but no index includes $TENANT_FIELD"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi
    fi

    # Tables with soft-delete should have at least one index referencing the soft-delete column
    if [[ -n "$sd_col" ]]; then
      has_sd_index=$(jq --arg t "$table_name" --arg sd "$sd_col" \
        '[.tables[] | select(.name == $t) | .indexes[] | .columns[] | select(. == $sd)] | length' "$DATA_REL")
      if [[ $has_sd_index -gt 0 ]]; then
        echo "  [OK] $table_name: has index including $sd_col"
      else
        echo "  [X] $table_name: has soft-delete column $sd_col but no index references it"
        VIOLATIONS=$((VIOLATIONS + 1))
      fi
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS index strategy violation(s)"
  exit 1
fi

echo ""
echo "[PASS] Index strategy verified"
exit 0
