#!/bin/bash
# scripts/verify-no-deferred-pages.sh
# GENERATED BY AGENT 6 - DO NOT EDIT MANUALLY
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== Phase 5: No Deferred Pages Implemented ==="

UI_DEPS="$PROJECT_ROOT/docs/ui-api-deps.json"
VIOLATIONS=0

if [[ ! -f "$UI_DEPS" ]]; then
  echo "[FAIL] ui-api-deps.json not found"
  exit 1
fi

# Deferred pages must NOT have their component files created
PAGE_COUNT=$(jq '.pages | length' "$UI_DEPS")
if [[ $PAGE_COUNT -gt 0 ]]; then
  for i in $(seq 0 $((PAGE_COUNT - 1))); do
    page_scope=$(jq -r ".pages[$i].scope" "$UI_DEPS")
    page_file=$(jq -r ".pages[$i].filePath" "$UI_DEPS")

    if [[ "$page_scope" == "deferred" ]]; then
      if [[ -f "$PROJECT_ROOT/$page_file" ]]; then
        echo "  [X] Deferred page implemented: $page_file"
        VIOLATIONS=$((VIOLATIONS + 1))
      else
        echo "  [OK] Deferred page not implemented: $page_file"
      fi
    fi
  done
fi

if [[ $VIOLATIONS -gt 0 ]]; then
  echo ""
  echo "[FAIL] $VIOLATIONS deferred page(s) have been implemented"
  exit 1
fi

echo ""
echo "[PASS] No deferred pages implemented"
exit 0
